name: 'dbt_healthcare'
version: '1.0.0'

profile: 'dbt_healthcare'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_healthcare:
    +materialized: view
    +schema: healthcare
